name: Home build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - run: yarn export
      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: out/
